port: 8001
database:
  driver: "mysql"
  host: "localhost"
  port: "3306"
  user: "root"
  password: "pintar123"
  db_name: "digtalent_microservice_auth"
  config: "charset=utf8&parseTime=True&loc=Local"