port: 8002
auth_service:
  host: "http://localhost:8001"
database:
  driver: "mysql"
  host: "localhost"
  port: "3306"
  user: "root"
  password: "pintar123"
  db_name: "digtalent_microservice_transaction"
  config: "charset=utf8&parseTime=True&loc=Local"